# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TranswideLogisticsDriver' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'MBProgressHUD'
   pod 'SwiftyJSON'
   pod 'SDWebImage'
   pod 'IQKeyboardManagerSwift'
   pod 'Firebase/Auth'
   pod 'Firebase/Core'
   pod 'Firebase/Messaging'
   pod 'GoogleMaps'
   pod 'GooglePlaces'
   pod 'CustomIOSAlertView', '~> 0.9.5'
   pod 'Cosmos'
   pod 'Firebase/Analytics'
   pod 'Alamofire', '~> 4.9.0'
   pod 'Firebase/Database'

  # Pods for TranswideLogisticsDriver

  target 'TranswideLogisticsDriverTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TranswideLogisticsDriverUITests' do
    # Pods for testing
  end

end
